### ISSUE TITLE
can't find solc

### ISSUE THREAD

**Issue by tjayrush** [gmtDevs/atom-ethereum-interface#1]
I'll probably be able to figure this out myself, but your instruction might be improved if you add a section explaining that the sole compiler has to be available.

[Enter steps to reproduce below:]

1. Followed instructions for loading up the atom extension. Work okay. A tiny bit confusing about localhost:8545, but I figured it out. You could have said something like "search for..." after telling user to open vi.

2. Opened a smart contract in Atom. Hit Cntl+Alt+C.  Pleased to see it worked, but it cannot find the solc. Instructions for how to install solc would have been appreciated.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-solidity](https://github.com/gmtcreators/atom-solidity) package, v0.0.0

### Stack Trace

Uncaught Error: eth_compileSolidity method not available: solc (solidity compiler) not found

```
At /Users/jrush/src.GitHub/atom-solidity/node_modules/web3/lib/web3/requestmanager.js:61

Error: eth_compileSolidity method not available: solc (solidity compiler) not found
    at Object.module.exports.InvalidResponse (/Users/jrush/src.GitHub/atom-solidity/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/jrush/src.GitHub/atom-solidity/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/jrush/src.GitHub/atom-solidity/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/jrush/src.GitHub/atom-solidity/lib/atom-solidity.coffee:74:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/jrush/src.GitHub/atom-solidity/lib/atom-solidity.coffee:47:13)
    at Object.module.exports.AtomSolidity.compile (/Users/jrush/src.GitHub/atom-solidity/lib/atom-solidity.coffee:64:10)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-solidity:compile (/Users/jrush/src.GitHub/atom-solidity/lib/atom-solidity.coffee:30:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.5.0 atom-solidity:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-solidity, v0.0.0

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
Here it is described how to install solc [installing-a-compiler](https://github.com/ethereum/go-ethereum/wiki/Contract-Tutorial#installing-a-compiler).
I will try to make some config editor to setup rpc connection as soon as I get some time.
