### ISSUE TITLE
Uncaught Error: solc: exit status 1Unknown exception during compilation.

### ISSUE THREAD

**Issue by ghost** [gmtDevs/atom-ethereum-interface#10]
I'm using Atom 1.8 and recently installed atom-ethereum-interface package. Compiler doesn't seem to work on my machine.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0
### Stack Trace

Uncaught Error: solc: exit status 1
Unknown exception during compilation.

```
At /Users/bahtiyar/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: solc: exit status 1
Unknown exception during compilation.

    at Object.module.exports.InvalidResponse (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/bahtiyar/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/bahtiyar/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -8:44.8.0 pane:show-item-1 (atom-pane.pane.active)
     -8:44 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -8:42.5.0 pane:show-item-1 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:13.8.0 grammar-selector:show (atom-text-editor.editor)
     -0:01.6.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-ethereum-interface": {}
}
```
### Installed Packages

``` coffee
# User
atom-ethereum-interface, v0.1.0-0
autocomplete-clang, v0.9.3
autocomplete-solidity, v0.2.0
build, v0.64.0
busy, v0.5.0
language-ini, v1.16.0
linter, v1.11.10
linter-gcc, v0.6.14
linter-solidity, v0.2.1
minimap, v4.24.6
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
platformio-ide, v1.2.2
platformio-ide-terminal, v2.0.10
project-manager, v2.9.7
script-runner, v1.8.4
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
Please see #7 I think this is same problem.

**Comment by Silur** [comment]
I've got the same error with latest ethereum, solc, geth, and package versions, console compiling works perfectly

**Comment by Silur** [comment]
seems like the plugin wants to parse the welcome message given by solc:
```
> I0623 14:37:34.157705 common/compiler/solidity.go:114] solc, the solidity compiler commandline interface
Version: 0.3.5-5f97274a/Release-Linux/g++/Interpreter

path: /usr/bin/solc
```

**Comment by 0mkara** [comment]
Thank you for pointing it out. I will keep an eye to the update.

**Comment by phiferd** [comment]
I'm getting this error on Windows as well.  I have verified that the command line works, but when try to compile in atom, I get:

```
Error: solc: exit status 1
Unknown exception during compilation.
    at Object.module.exports.InvalidResponse (C:\Users\Kate\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\errors.js:35:16)
    at RequestManager.send (C:\Users\Kate\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\requestmanager.js:61:22)
    at Object.send [as solidity] (C:\Users\Kate\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\method.js:145:58)
    at file:///C:/Users/Kate/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (file:///C:/Users/Kate/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (file:///C:/Users/Kate/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (file:///C:/Users/Kate/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Kate\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Kate\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Kate\AppData\Local\atom\app-1.9.8\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Kate\AppData\Local\atom\app-1.9.8\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\Kate\AppData\Local\atom\app-1.9.8\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by bellaj** [comment]
just update the geth 
and start it without rpc with the console 
afterward launch the rpc server admin.startRPC("127.0.0.1", 8545, "*", "web3,db,net,eth")
