### ISSUE TITLE
Uncaught Error: solc: exit status 1Unknown exception during compilation.

### ISSUE THREAD

**Issue by Silur** [gmtDevs/atom-ethereum-interface#13]
1. paste ethereum "mortal" example into atom
2. Compile code

**Atom Version**: 1.8.0
**System**: linux 4.6.2-1-ARCH
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0

### Stack Trace

Uncaught Error: solc: exit status 1
Unknown exception during compilation.

```
At /home/silur/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: solc: exit status 1
Unknown exception during compilation.

    at Object.module.exports.InvalidResponse (/home/silur/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/home/silur/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/home/silur/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /home/silur/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/home/silur/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/home/silur/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/home/silur/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -8:41.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:15.9.0 eth-interface:compile (atom-text-editor.editor.is-focused)
     -8:03.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -7:43.3.0 core:confirm (atom-text-editor#atom-ethereum-interface.rpcAddress.editor.mini.is-focused)
     -7:16 color-picker:open (atom-text-editor.editor.is-focused)
     -7:11.1.0 eth-interface:compile (atom-text-editor.editor.is-focused)
     -7:09.3.0 color-picker:open (atom-text-editor.editor.is-focused)
     -6:39 grammar-selector:show (atom-text-editor.editor)
     -6:26.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -6:26.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:30.4.0 grammar-selector:show (atom-text-editor.editor)
  4x -5:27.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:00.3.0 eth-interface:build (atom-text-editor.editor.is-focused)
     -0:56.9.0 eth-interface:compile (atom-text-editor.editor.is-focused)
     -0:28.1.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:23.7.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "atom-ethereum-interface": {}
}
```

### Installed Packages

```coffee
# User
atom-ethereum-interface, v0.1.0-0
autocomplete-paths, v1.0.2
color-picker, v2.1.1
language-kotlin, v0.4.0
linter, v1.11.4
linter-eslint, v7.2.0
merge-conflicts, v1.4.2

# Dev
No dev packages
```

**Comment by Silur** [comment]
sorry for duplication of #10
