### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by alibeyaz1** [gmtDevs/atom-ethereum-interface#14]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0
### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /C:/Users/AL%C4%B0/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:192

TypeError: Cannot read property 'getText' of undefined
    at Object.module.exports.AtomSolidity.compile (file:///C:/Users/ALİ/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:118:24)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (file:///C:/Users/ALİ/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\ALİ\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -5:31.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:27.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:27 core:select-all (atom-text-editor.editor.is-focused)
  2x -4:26.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:58 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:33 core:undo (atom-text-editor.editor.is-focused)
     -0:49.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:18.6.0 core:confirm (atom-text-editor#atom-ethereum-interface.rpcAddress.editor.mini.is-focused)
     -0:03.4.0 eth-interface:compile (div.package-detail.panels-item)
```
### Config

``` json
{
  "atom-ethereum-interface": {}
}
```
### Installed Packages

``` coffee
# User
atom-ethereum-interface, v0.1.0-0

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
Please update and check. Thanks!
