### ISSUE TITLE
 Uncaught Error: solc: no build results found

### ISSUE THREAD

**Issue by CyberNano** [gmtDevs/atom-ethereum-interface#17]
[Enter steps to reproduce below:]
1. I made sure I had solc installed on geth as well as running on the correct port.
2. I am using Windows 10.

**Atom Version**: 1.9.9
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0
### Stack Trace

Uncaught Error: solc: no build results found

```
At C:\Users\felix\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\requestmanager.js:61

Error: solc: no build results found
    at Object.module.exports.InvalidResponse (C:\Users\felix\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\errors.js:35:16)
    at RequestManager.send (C:\Users\felix\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\requestmanager.js:61:22)
    at Object.send [as solidity] (C:\Users\felix\.atom\packages\atom-ethereum-interface\node_modules\web3\lib\web3\method.js:145:58)
    at file:///C:/Users/felix/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (file:///C:/Users/felix/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (file:///C:/Users/felix/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (file:///C:/Users/felix/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\felix\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\felix\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\felix\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\felix\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\felix\AppData\Local\atom\app-1.9.9\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

Any ideas on how to get it working, I really would like to use this.

Thanks!

**Comment by 0mkara** [comment]
Please update and check again. Thanks!
