### ISSUE TITLE
Uncaught TypeError: value.forEach is not a function

### ISSUE THREAD

**Issue by mcoblenz** [gmtDevs/atom-ethereum-interface#22]
[Enter steps to reproduce below:]
1. Copy/paste Ballot contract from https://solidity.readthedocs.io/en/latest/solidity-by-example.html into an Atom editor window.
2. Compile.
3. Build compiled.
4. Click Create.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0
### Stack Trace

Uncaught TypeError: value.forEach is not a function

```
At /Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactErrorUtils.js:53

TypeError: value.forEach is not a function
    at /Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/solidity/type.js:156:19
    at SolidityType.encode (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/solidity/type.js:161:11)
    at /Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/solidity/coder.js:86:29
    at Array.map (native)
    at SolidityCoder.encodeParams (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/solidity/coder.js:85:34)
    at /Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/web3/contract.js:44:22
    at Array.map (native)
    at encodeConstructorParams (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/web3/contract.js:43:8)
    at new (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/web3/lib/web3/contract.js:196:21)
    at /Users/mcoblenz/code/atom-ethereum-interface/lib/ethereum-interface.coffee:311:17
    at Object.module.exports.AtomSolidity.prepareEnv (/Users/mcoblenz/code/atom-ethereum-interface/lib/ethereum-interface.coffee:242:13)
    at Object.module.exports.AtomSolidity.create (/Users/mcoblenz/code/atom-ethereum-interface/lib/ethereum-interface.coffee:298:10)
    at React.createClass._handleSubmit (/Users/mcoblenz/code/atom-ethereum-interface/lib/ethereum-interface.coffee:231:30)
    at Object.invokeGuardedCallback (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactErrorUtils.js:27:12)
    at executeDispatch (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/EventPluginUtils.js:79:21)
    at Object.executeDispatchesInOrder (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/EventPluginUtils.js:102:5)
    at executeDispatchesAndRelease (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/EventPluginHub.js:43:22)
    at executeDispatchesAndReleaseTopLevel (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/EventPluginHub.js:54:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/EventPluginHub.js:259:7)
    at runEventQueueInBatch (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactEventEmitterMixin.js:34:5)
    at handleTopLevelWithoutPath (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactEventListener.js:93:24)
    at handleTopLevelImpl (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactEventListener.js:73:3)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactUpdates.js:94:20)
    at ReactEventListener.dispatchEvent (/Users/mcoblenz/code/atom-ethereum-interface/node_modules/react/lib/ReactEventListener.js:204:20)
```
### Commands

```
     -8:52.6.0 core:paste (input.call-button-values)
     -8:16.7.0 core:copy (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
     -8:14.7.0 application:new-file (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
     -8:14 core:paste (atom-text-editor.editor.is-focused)
     -8:12.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -3:55.4.0 core:copy (div.atom-solidity.native-key-bindings)
  2x -1:57.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:56.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:54.3.0 eth-interface:compile (atom-text-editor.editor.is-focused)
     -1:49.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:12.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:10.7.0 eth-interface:compile (atom-text-editor.editor.is-focused)
     -1:07.3.0 eth-interface:build (atom-text-editor.editor.is-focused)
     -0:12 eth-interface:compile (atom-text-editor.editor.is-focused)
     -0:08.0 eth-interface:build (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "atom-ethereum-interface": {
    "rpcAddress": "http://localhost:8545"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ethereum-interface, v0.1.0-0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
Please update and try again.

**Comment by 0mkara** [comment]
Closed for inactivity.

**Comment by samnet** [comment]
@0mkara Hello Omkara, I am having the same issue mcoblenz.
