### ISSUE TITLE
Uncaught Error: solc: signal: segmentation fault

### ISSUE THREAD

**Issue by always-sunny** [gmtDevs/atom-ethereum-interface#7]
[Enter steps to reproduce below:]

1. Downloaded atom-ethereum-interface
2. Copied and compiled the 'basic token' from https://www.ethereum.org/token 
3. How do I get the package to give me colored syntax? 

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0

### Stack Trace

Uncaught Error: solc: signal: segmentation fault

```
At /Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: solc: signal: segmentation fault

    at Object.module.exports.InvalidResponse (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:08.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.4.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-ethereum-interface": {
    "rpcAddress": " http://localhost:8545/"
  }
}
```

### Installed Packages

```coffee
# User
Desktop, vundefined
Ryan, vundefined
atom-ethereum-interface, v0.1.0-0
pigments, v0.26.3

# Dev
No dev packages
```

-thank you

**Comment by 0mkara** [comment]
I just compiled the token contract you pointed to. It did not produced any error. Can you please provide outputs of `eth.getCompilers()` from your geth console ?

**Comment by always-sunny** [comment]
I0525 13:05:45.936995 common/compiler/solidity.go:114] solc, the solidity compiler commandline interface
Version: 0.3.2-0a37072e/Release-Darwin/appleclang/JIT

path: /usr/local/bin/solc
[]
> 


That is my output for eth.gethCompilers()

Now when I started **geth --testnet console** and try to compile the code it says could not could connect to local geth instance. When I start geth using **geth --rpc --rpcapi="db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --rpccorsdomain "localhost" console** it gives me the error I posted. 

And as for the directory in which I put atom-ethereum-interface, I made a directory on my desktop where I put it, and for the syntax folder, I put that in atom.app next to contents?

**Comment by always-sunny** [comment]
And for when you configure the settings, when you click the text box it'll pull up the default localhost but if it is the default local host it goes back to the greyed out backdrop text when you click out of the text box. So I had to put a space in front of the text for the default http://localhost:8545/ to stay

**Comment by 0mkara** [comment]
Please try to start geth with
```
geth --rpc --rpcapi="db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --rpccorsdomain "*" console
```
Let me know if that works.

**Comment by always-sunny** [comment]
@0mkara 

Didn't work. Ended up with another error: 
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0


### Stack Trace

Uncaught Error: solc: signal: segmentation fault


```
At /Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: solc: signal: segmentation fault

    at Object.module.exports.InvalidResponse (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -2:17.7.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:09.7.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-ethereum-interface": {}
}
```

### Installed Packages

```coffee
# User
Desktop, vundefined
Ryan, vundefined
atom-ethereum-interface, v0.1.0-0
language-ethereum, v0.3.8

# Dev
No dev packages
```

Syntax coloring still not in effect.

**Comment by 0mkara** [comment]
I think your problem is something like [this](https://forum.ethereum.org/discussion/3512/cant-compile-a-contract). Please try to compile example greeter contract from commandline. Please inform me what happens.

**Comment by always-sunny** [comment]
@0mkara 

[Enter steps to reproduce below:]

1. Copied and pasted example greeter contract: var greeterSource = 'contract mortal { address owner; function mortal() { owner = msg.sender; } function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { string greeting; function greeter(string _greeting) public { greeting = _greeting; } function greet() constant returns (string) { return greeting; } }'

var greeterCompiled = web3.eth.compile.solidity(greeterSource)
2. Received this error:

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0


### Stack Trace

Uncaught Error: solc: exit status 1
<stdin>:1:1: Error: Expected import directive or contract definition.
var greeterSource = 'contract mortal { address owner; function mortal() { owner = msg.sender; } function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { string greeting; function greeter(string _greeting) public { greeting = _greeting; } function greet() constant returns (string) { return greeting; } }'
^


```
At /Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: solc: exit status 1
<stdin>:1:1: Error: Expected import directive or contract definition.
var greeterSource = 'contract mortal { address owner; function mortal() { owner = msg.sender; } function kill() { if (msg.sender == owner) suicide(owner); } } contract greeter is mortal { string greeting; function greeter(string _greeting) public { greeting = _greeting; } function greet() constant returns (string) { return greeting; } }'
^

    at Object.module.exports.InvalidResponse (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/Ryan/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/Ryan/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:21.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:15.6.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "atom-ethereum-interface": {}
}
```

### Installed Packages

```coffee
# User
Desktop, vundefined
Ryan, vundefined
atom-ethereum-interface, v0.1.0-0
language-ethereum, v0.3.8

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
I think this is your ethereum installation issue. Please install latest version of geth and solidity.

**Comment by always-sunny** [comment]
@0mkara 

It worked!

I did 
1) **brew update/upgrade**
2) **git clone https://github.com/ethereum/go-ethereum**
3) **cd go-ethereum**
4)  **make geth**

**_I still can't get the syntax coloring working if there's any advice/help you could give me_**

-Thank you for all the help on this one btw, really appreciate it

**Comment by 0mkara** [comment]
syntax coloring is done by https://atom.io/packages/language-ethereum
