### ISSUE TITLE
Uncaught Error: Internal error

### ISSUE THREAD

**Issue by johnwhitton** [gmtDevs/atom-ethereum-interface#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-ethereum-interface](https://github.com/gmtDevs/atom-ethereum-interface) package, v0.1.0-0

### Stack Trace

Uncaught Error: Internal error

```
At /Users/johnwhitton/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61

Error: Internal error
    at Object.module.exports.InvalidResponse (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/errors.js:35:16)
    at [object Object].RequestManager.send (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Object.send [as solidity] (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/node_modules/web3/lib/web3/method.js:145:58)
    at /Users/johnwhitton/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:129:50
    at Object.module.exports.AtomSolidity.checkConnection (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:69:13)
    at Object.module.exports.AtomSolidity.compile (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:119:10)
    at atom-workspace.subscriptions.add.atom.commands.add.eth-interface:compile (/Users/johnwhitton/.atom/packages/atom-ethereum-interface/lib/ethereum-interface.coffee:37:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -2:37.6.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:55.7.0 compare-files:compare (atom-text-editor.editor.is-focused)
     -1:45.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:28.8.0 compare-files:compare (atom-text-editor.editor.is-focused)
     -0:00.7.0 eth-interface:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ethereum-interface, v0.1.0-0
atom-handlebars, v1.3.0
atom-json-editor, v0.4.1
auto-indent, v0.5.0
autocomplete-paths, v1.0.2
color-picker, v2.1.1
command-logger, v0.23.0
compare-files, v0.6.2
editor-stats, v0.17.0
editorconfig, v1.4.1
floobits, v0.31.3
language-actionscript3, v0.3.0
language-ethereum, v0.3.8
linter, v1.11.4
merge-conflicts, v1.4.3
polymer-atom, v0.0.8
pretty-json, v1.4.0
project-manager, v2.9.7
react, v0.15.0

# Dev
No dev packages
```

**Comment by 0mkara** [comment]
I think this is same as #7
